# Generated by Django 3.0.4 on 2020-03-24 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salvager', '0002_auto_20200323_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(max_length=1000)),
                ('content', models.TextField(max_length=3000)),
                ('rating', models.FloatField()),
                ('username', models.CharField(max_length=100)),
                ('pub_time', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='salvager.Product')),
            ],
        ),
    ]
