# Generated by Django 3.0.4 on 2020-04-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salvager', '0004_auto_20200324_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=3000)),
            ],
        ),
    ]
