# Generated by Django 3.0.4 on 2020-04-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salvager', '0005_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diary_images')),
                ('headline', models.TextField(max_length=3000)),
                ('content', models.TextField(max_length=6000)),
                ('created_by', models.CharField(max_length=100)),
                ('pub_time', models.DateTimeField()),
            ],
        ),
    ]
